### ISSUE TITLE
Emotes no longer working with the newest FFZ

### ISSUE THREAD

**Issue by LawlyPopz** [Lordmau5/BTTV4FFZ#8]
Emotes are no longer showing in the chat!

**Comment by LawlyPopz** [comment]
In the FFZ emote menu the BTTV channel emotes don't show up.
The global BTTV emotes are still visible.
The BTTV4FFZ option sub-menu inside the FFZ option menu is still visible.

**Comment by jnki** [comment]
I have same problem.

this shows up in log, not sure if helpful

>Ext "BetterTTV": Error in On-Room Callback: TypeError: Cannot read property 'joinChannel' of undefined
Ext "BetterTTV": Error in On-Room Callback: TypeError: Cannot read property 'joinChannel' of undefined

**Comment by Lordmau5** [comment]
Oh I'm a f*cking derp. Fix coming up as soon as I get home >_<'

**Comment by Lordmau5** [comment]
Should be fixed in v1.3.2 - please check and respond if it actually *did* fix it :)

**Comment by LawlyPopz** [comment]
thats fixed but emoted no longer show in pins chats or hosted chats

**Comment by LawlyPopz** [comment]
i have found the issue.... if you have Enable BTTV Pro Emotes enabled this it removed the regular emotes

**Comment by Lordmau5** [comment]
Oh that's interesting, I'll run some tests and see if I can figure it out! :)

**Comment by jnki** [comment]
the channel emotes are still not showing up for me. it says v1.3.2 in debug section.

they were there briefly, but after refreshing the pages, i can't get them back. :open_mouth: 

same message in log

**Comment by LawlyPopz** [comment]
Stops working when u enable the pro emotes Kappa

**Comment by Lordmau5** [comment]
Should be fixed completely now, even when pro emotes are enabled :D
Please respond once again, even though I'm like 99% sure now :P

**Comment by jnki** [comment]
seems to be working now!

thank you!

**Comment by LawlyPopz** [comment]
That would be wrong BTTV Pro emotes no longer work!

**Comment by Lordmau5** [comment]
@LawlyPopz Huh? What do you mean by that?

**Comment by LawlyPopz** [comment]
http://pushzz.xyz/img/c8f04.png <<< they no longer show!

**Comment by Lordmau5** [comment]
Okay, different question, @LawlyPopz :

When you said that they don't work anymore, did you just re-enable it in the BTTV4FFZ Twitch settings?
You might need to refresh the window, if you haven't done that at that point :P

I can fix that up when I get home today so it will connect / disconnect dynamically, so don't worry about it that much.
I do however need another confirmation then :P

**Comment by LawlyPopz** [comment]
http://pushzz.xyz/img/6c42b.png but look no BTTV Pro http://pushzz.xyz/img/499fd.png

**Comment by Lordmau5** [comment]
Closing this down because I am pretty sure that stuff is working as intended again.
Haven't heard pf any issues recently.

**Comment by LawlyPopz** [comment]
![a52d7](https://cloud.githubusercontent.com/assets/9284733/17462864/9d8e49e4-5cb1-11e6-8dd1-775546c6bc19.png) is still broken 
![af1a4](https://cloud.githubusercontent.com/assets/9284733/17462868/c4a556c6-5cb1-11e6-819b-26c55f714a75.png) when it should look like this 
![2ea2e](https://cloud.githubusercontent.com/assets/9284733/17462873/cbd43084-5cb1-11e6-99e8-ca1907373cd7.png)

Please fix this so i can remove the version i'm using to come back to using yours i have given you the code above to fix this
